### ISSUE TITLE
Typescript support 

### ISSUE THREAD

**Issue by micaelillos** [topazbarziv/Webtop_Covid19Sign#1]
Is there a typescript version ?

**Comment by planecore** [comment]
It’s JavaScript, not TypeScript. SHAME.

**Comment by planecore** [comment]
Crap I’m a collaborator lol

**Comment by micaelillos** [comment]
> Crap I’m a collaborator lol

Lollllllll

**Comment by topazbarziv** [comment]
> Is there a typescript version ?

Not at the moment.

**Comment by planecore** [comment]
Noooooo I’m not a collaborator anymore

**Comment by topazbarziv** [comment]
> Noooooo I’m not a collaborator anymore

You've never used a Smart School in your life at all.
